#!/bin/sh
echo "****************************************"
echo "*Please .. Restart Enigma2 *"
echo "****************************************"
echo "* Enjoy our plugin *"
echo "****************************************"
echo "* All Rights Reserved *"
echo "* © 2024 - Lululla *"
echo "****************************************"
#init 4
#killall -9 enigma2 > /dev/null 2>&1
#init 3
exit 0
